# Generated by Django 5.2.8 on 2025-12-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_studentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('bg_gradient_from', models.CharField(default='blue-600', help_text='Tailwind color class (e.g. blue-600)', max_length=50)),
                ('bg_gradient_to', models.CharField(default='purple-600', help_text='Tailwind color class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
